//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMVPDataBasePart
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArchBaseEntity : DbContext
    {
        public ArchBaseEntity(string InLog, string InPass)
            : base("Data Source = DESKTOP - I53NOBN; Initial Catalog = ArcheageDataBase; Integrated Security = True; Persist Security Info=True;User ID = " + InLog + "; Password=" + InPass + ";")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventBase> EventBase { get; set; }
        public virtual DbSet<EventRemindTable> EventRemindTable { get; set; }
        public virtual DbSet<EventTimeTable> EventTimeTable { get; set; }
    
        public virtual int CheckUser(ObjectParameter inResulter, string inName, string inPass)
        {
            var inNameParameter = inName != null ?
                new ObjectParameter("InName", inName) :
                new ObjectParameter("InName", typeof(string));
    
            var inPassParameter = inPass != null ?
                new ObjectParameter("InPass", inPass) :
                new ObjectParameter("InPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckUser", inResulter, inNameParameter, inPassParameter);
        }
    
        public virtual int GetNowUserID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNowUserID");
        }
    }
}
