//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMVPDataBasePart
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseInfoView
    {
        public decimal EventID { get; set; }
        public short UserID { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public string EventName { get; set; }
        public Nullable<int> ReminderCount { get; set; }
        public Nullable<System.TimeSpan> EventDuration { get; set; }
        public Nullable<decimal> EverywhatRemind { get; set; }
    }
}
