//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMVPDataBasePart
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRemindTable
    {
        public System.TimeSpan RemindBeforeAfter { get; set; }
        public Nullable<decimal> TypeOfRemind { get; set; }
        public Nullable<System.DateTime> DateUntilRemind { get; set; }
        public decimal EventID { get; set; }
        public short UserID { get; set; }
    
        public virtual EventBase EventBase { get; set; }
    }
}
